# -*- coding: utf-8 -*-
"""رشته‌های ترجمه‌شده برای سیستم تجارت.

این فایل فقط داده‌ست. از trade_system.py اصلی (نسخه تلگرام) کپی شده
و شامل همه‌ی رشته‌های fa/en/tr هست.

نکته: کلیدها باید در هر سه زبان یکسان باشن — init() این رو assert می‌کنه.
"""

STRINGS = {
    'fa': {
        # ============ عمومی ============
        'err_generic': "خطایی رخ داد. دوباره تلاش کنید.",
        'session_expired': "جلسه تجارت یافت نشد. از دکمه «🚢 تجارت جهانی» دوباره شروع کنید.",
        'not_registered': "این گروه هنوز لردی ندارد. ابتدا با /setlord ثبت‌نام کنید.",
        'not_lord': "فقط لرد این گروه می‌تواند این کار را انجام دهد.",
        'admin_only': "شما ادمین نیستید.",
        'owner_only': "فقط مالک ربات می‌تواند این کار را انجام دهد.",
        'already_handled': "این پیشنهاد دیگر معتبر نیست.",

        # ============ منوی تجارت ============
        'menu_title': "🌍 تجارت جهانی\n\nنوع تجارت را انتخاب کنید قربان:",
        'menu_active': "\n\n🧭 تجارت‌های در جریان شما: {n}",
        'btn_sea': "🚢 تجارت دریایی",
        'btn_land': "🐫 تجارت زمینی",
        'mode_sea': "دریایی",
        'mode_land': "زمینی",
        'need_home': "🏠 موقعیت {mode} گروه شما هنوز توسط ادمین تعیین نشده است.",
        'no_dest': "مقصدی برای تجارت {mode} در دسترس نیست؛ گروه‌های دیگر باید موقعیت داشته باشند.",
        'choose_dest': "🎯 مقصد تجارت را انتخاب کنید:",

        # ============ دکمه‌های عمومی ============
        'btn_cancel': "❌ لغو",
        'btn_prev': "➡️ قبلی",
        'btn_next': "بعدی ⬅️",
        'btn_back': "🔙 بازگشت",

        # ============ کالاها ============
        'goods_title': "📦 کالاهای تجارت را انتخاب کنید:\n{lines}\n\n📊 حجم کل بار: {vol}",
        'goods_none': "هنوز کالایی انتخاب نشده",
        'btn_goods_done': "✅ ادامه",
        'ask_amount': "مقدار {res} را وارد کنید (موجودی: {bal}):",
        'bad_number': "مقدار وارد شده معتبر نیست. لطفا یک عدد وارد کنید.",
        'too_much': "بیشتر از موجودی شماست (موجودی: {bal}).",
        'need_goods': "حداقل یک کالا انتخاب کنید.",

        # ============ وسایل حمل ============
        'veh_title_sea': "⚓️ ناوگان تجاری را انتخاب کنید:\n{fleet}\n\n🧾 انتخاب شما:\n{lines}\n\n📦 حجم بار: {vol}\n🚢 ظرفیت ناوگان: {cap}",
        'veh_title_land': "🐫 کاروان تجاری را آماده کنید:\n{fleet}\n\n🧾 انتخاب شما:\n{lines}\n\n📦 حجم بار: {vol}\n🐫 ظرفیت کاروان‌ها: {cap}\n💵 هزینه هر کاروان در این سفر: {p} پول",
        'ask_vcount': "تعداد {v} را وارد کنید (در اختیار: {bal} | ظرفیت هرکدام: {cap}):",
        'veh_row': "{name}: ظرفیت هرکدام {cap} — در اختیار شما {own}",
        'ask_caravans': "تعداد کاروان را وارد کنید (در اختیار: {bal} | ظرفیت هرکدام: {cap} | هزینه هر کاروان {p} پول):",
        'not_enough_units': "بیشتر از تعداد موجود است (موجودی: {bal}).",
        'not_enough_cap': "ظرفیت کافی نیست! حجم بار {vol} است اما ظرفیت فقط {cap}.",
        'btn_veh_done': "🗺 محاسبه مسیرها",

        # ============ مسیر ============
        'routes_title': "🗺 مسیرهای پیشنهادی از {src} به {dst}:",
        'route_fast': "⚡️ سریع‌ترین مسیر",
        'route_free': "🆓 مسیر بدون عوارض",
        'route_cheap': "💰 ارزان‌ترین مسیر",
        'route_block': "{label}\n⏱ مدت سفر: {dur}\n🧭 مسیر: {path}\n💵 کارمزد: {fee}\n🪙 عوارض: {tolls}\n💰 هزینه کل: {total}",
        'tolls_none': "ندارد",
        'no_route': "مسیری بین این دو موقعیت پیدا نشد!",
        'btn_route': "انتخاب مسیر {i}",
        'path_arrow': " ← ",

        # ============ تأیید و ارسال ============
        'confirm_title': "📜 خلاصه تجارت:\n🎯 مقصد: {dest}\n📦 کالاها:\n{goods}\n🚛 وسایل: {veh}\n🧭 مسیر: {path}\n⏱ مدت سفر: {dur}\n💰 هزینه کل (کارمزد + عوارض): {cost} پول\n\nتایید می‌کنید قربان؟",
        'btn_send': "✅ ارسال پیشنهاد",
        'insufficient': "💸 موجودی شما برای این تجارت کافی نیست.",
        'offer_sent_sender': "📨 پیشنهاد تجارت #{tid} به {dest} ارسال شد. در انتظار پذیرش لرد مقصد...",
        'btn_cancel_offer': "🚫 لغو پیشنهاد",
        'send_failed': "ارسال پیشنهاد به گروه مقصد ممکن نبود؛ همه مبالغ بازگردانده شد.",

        # ============ پیشنهاد به گیرنده ============
        'offer_msg': "📦 پیشنهاد تجارت #{tid}\n\n🌍 از: {sender}\n👤 لرد: {lord}\n\n📦 کالاها:\n{goods}\n\n🧭 مسیر: {path}\n⏱ مدت سفر پس از پذیرش: {dur}\n⌛️ مهلت پذیرش: {exp} دقیقه\n\nآیا این تجارت را می‌پذیرید؟",
        'btn_accept': "✅ پذیرش",
        'btn_decline': "❌ رد",
        'offer_accepted_edit': "\n\n✅ پذیرفته شد — محموله حرکت کرد!",
        'offer_declined_edit': "\n\n❌ رد شد.",
        'offer_cancelled_edit': "\n\n🚫 توسط فرستنده لغو شد.",
        'offer_expired_edit': "\n\n⌛️ مهلت پذیرش تمام شد.",
        'declined_sender': "❌ پیشنهاد تجارت #{tid} رد شد؛ کالاها و هزینه‌ها بازگردانده شد.",
        'cancelled_sender': "🚫 پیشنهاد تجارت #{tid} لغو شد؛ مبالغ بازگردانده شد.",
        'expired_sender': "⌛️ پیشنهاد تجارت #{tid} منقضی شد؛ مبالغ بازگردانده شد.",

        # ============ ردیابی محموله ============
        'track_header': "{emoji} تجارت #{tid} | از {src_g} به {dst_g}",
        'track_moving': "🧭 در حرکت به سوی {next} (حدود {min} دقیقه)",
        'track_at': "📍 موقعیت فعلی: {cur}",
        'track_choke': "🪙 محموله از {cur} عبور کرد (عوارض پرداخت شد)",
        'track_cape': "🌊 محموله {cur} را دور زد",
        'track_done': "✅ محموله به مقصد رسید و کالاها تحویل شد!",
        'track_choke_owned': "🪙 محموله از {cur} عبور کرد — عوارض به {owner} پرداخت شد",
        'track_pass': "🌫 محموله از {cur} عبور کرد",
        'arrived_receiver': "📦 محموله تجارت #{tid} از {sender} رسید!\n{goods}",
        'depart_channel': "{emoji} محموله تجاری از {src_g} به مقصد {dst_g} حرکت کرد!\n\n🧭 مسیر: {path}\n⏱ زمان تقریبی رسیدن: {dur}",
        'arrive_channel': "{emoji} محموله تجاری از {src_g} به {dst_g} رسید و بار تحویل شد!",

        # ============ زمان ============
        'dur_hm': "{h} ساعت و {m} دقیقه",
        'dur_m': "{m} دقیقه",
        'wizard_cancelled': "🚫 تجارت لغو شد.",

        # ============ پنل ادمین ============
        'adm_title': "🌍 مدیریت تجارت:",
        'btn_home_sea': "⚓️ تعیین موقعیت دریایی گروه‌ها",
        'btn_home_land': "🏔 تعیین موقعیت زمینی گروه‌ها",
        'btn_cfg': "⚙️ تنظیمات تجارت",
        'btn_owners': "🪙 مالکیت تنگه‌ها و گذرگاه‌ها",
        'btn_map': "🗺 ویرایش نقشه تجارت",
        'adm_pick_group': "گروه را انتخاب کنید:",
        'adm_pick_node': "موقعیت {mode} را برای {g} انتخاب کنید:",
        'home_set': "🏠 موقعیت {mode} گروه {g} روی «{node}» تنظیم شد.",
        'adm_no_groups': "هیچ کشوری ثبت نشده است.",

        # ============ مالکیت ============
        'own_title': "🪙 تنگه‌ها و گذرگاه‌ها (صفحه {p}) — برای تعیین مالک روی یکی بزنید:",
        'own_unowned': "بدون مالک",
        'own_pick': "مالک {node} را انتخاب کنید:",
        'btn_no_owner': "🚫 بدون مالک",
        'own_set': "🪙 {node} از این پس در مالکیت {g} است و عوارض عبور به خزانه‌اش واریز می‌شود.",
        'own_cleared': "🪙 {node} دیگر مالکی ندارد؛ عوارض آن سوزانده می‌شود.",
        'toll_income': "🪙 خزانه شما {amount} پول عوارض دریافت کرد!\nمحموله تجارت #{tid} از {node} عبور کرد.",

        # ============ تنظیمات ============
        'cfg_home': "⚙️ تنظیمات تجارت — کدام دسته را می‌خواهید ببینید؟",
        'cfg_sec_journey': "⏱ سفر و کرایه ({n} مورد)",
        'cfg_sec_capacity': "📦 ظرفیت و هزینه وسایل حمل ({n} مورد)",
        'cfg_sec_toll': "🛣 عوارض گذرگاه‌ها ({n} مورد)",
        'cfg_sec_name_journey': "سفر و کرایه",
        'cfg_sec_name_capacity': "ظرفیت و هزینه وسایل حمل",
        'cfg_sec_name_toll': "عوارض گذرگاه‌ها",
        'cfg_sec_empty': "در این دسته چیزی برای تنظیم نیست.",
        'cfg_title': "⚙️ تنظیمات تجارت — {section} (صفحه {p} از {n})\nبرای تغییر، روی دکمه همان مورد بزنید:",
        'cfg_row': "**{name}** — الان: `{val}`\n{help}",
        'cfg_ask': "**{name}**\n{help}\n\nمقدار فعلی: {val}\nمقدار جدید را بفرستید:",
        'cfg_set': "✅ {name} روی {val} تنظیم شد.",
        'cfg_toll_label': "🛣 عوارض {node}",
        'cfg_toll_help': "هر محموله‌ای که از این گذرگاه رد شود چقدر عوارض بدهد. کشوری که مالک گذرگاه است رایگان رد می‌شود.",
        'btn_cfg_back': "🔙 دسته‌های تنظیمات",

        # نام تنظیمات
        'sea_min_per_unit': "⏱ زمان سفر دریایی",
        'land_min_per_unit': "⏱ زمان سفر زمینی",
        'fee_per_unit': "💵 کرایه مسیر",
        'offer_expiry_min': "⌛️ مهلت پاسخ به پیشنهاد",
        'cap_small': "⛵ ظرفیت بار کشتی کوچک",
        'cap_medium': "🚢 ظرفیت بار کشتی متوسط",
        'cap_large': "🛳 ظرفیت بار کشتی بزرگ",
        'cap_caravan': "🐫 ظرفیت بار هر کاروان",
        'caravan_cost': "💰 هزینه هر کاروان در هر سفر",

        # توضیح تنظیمات
        'help_sea_min_per_unit': "چند دقیقه طول بکشد تا یک ناوگان دریایی یک واحد فاصله را طی کند.",
        'help_land_min_per_unit': "چند دقیقه طول بکشد تا یک کاروان یک واحد فاصله را طی کند.",
        'help_fee_per_unit': "به ازای هر واحد از طول مسیر، چقدر پول از فرستنده گرفته شود.",
        'help_offer_expiry_min': "اگر گیرنده تا این تعداد دقیقه جواب ندهد، پیشنهاد باطل می‌شود.",
        'help_cap_small': "هر کشتی کوچک چند واحد کالا می‌برد.",
        'help_cap_medium': "هر کشتی متوسط چند واحد کالا می‌برد.",
        'help_cap_large': "هر کشتی بزرگ چند واحد کالا می‌برد.",
        'help_cap_caravan': "هر کاروان چند واحد کالا می‌برد.",
        'help_caravan_cost': "بابت هر کاروانی که در یک سفر راه می‌افتد، چقدر پول گرفته شود.",

        # ============ عکس تجارت ============
        'btn_photo': "🖼 عکس تجارت",
        'btn_ph_mode_sea': "🚢 عکس تجارت دریایی — {state}",
        'btn_ph_mode_land': "🐫 عکس تجارت زمینی — {state}",
        'btn_ph_mode_both': "🖼 عکس مشترک (پیش‌فرض) — {state}",
        'btn_ph_back': "🔙 بازگشت به عکس‌ها",
        'ph_home': "🖼 عکس تجارت — کدام را می‌خواهید تنظیم کنید؟",
        'ph_mode_sea': "تجارت دریایی",
        'ph_mode_land': "تجارت زمینی",
        'ph_mode_both': "عکس مشترک",
        'ph_shared': "از عکس مشترک استفاده می‌کند",
        'ph_title': "🖼 عکس {mode} — وضعیت فعلی: {state}\nاین عکس روی پیشنهاد تجارت، پیام رهگیری محموله و اعلان‌های کانال قرار می‌گیرد.",
        'ph_set': "تنظیم شده",
        'ph_unset': "تنظیم نشده",
        'btn_ph_set': "📷 تنظیم عکس",
        'btn_ph_clear': "🗑 حذف عکس",
        'ph_ask': "اکنون عکس {mode} را بفرستید:",
        'ph_saved': "✅ عکس {mode} ذخیره شد.",
        'ph_cleared': "🗑 عکس تجارت حذف شد؛ پیام‌ها دوباره متنی می‌شوند.",
        'ph_not_photo': "این پیام عکس نیست؛ عملیات لغو شد.",

        # ============ باز/بسته کردن تجارت ============
        'btn_trade_modes': "🚧 باز/بسته کردن تجارت کشورها",
        'tm_title': "🚧 تجارت هر کشور (صفحه {p} از {n}) — برای تغییر روی کشور بزنید:",
        'tm_group': "🚧 **{g}**\n{lines}",
        'tm_row': "{mode}: {state}",
        'tm_on': "{mode}✅",
        'tm_off': "{mode}🚫",
        'tm_state_on': "باز",
        'tm_state_off': "بسته",
        'btn_tm_close': "🚫 بستن {mode}",
        'btn_tm_open': "✅ باز کردن {mode}",
        'btn_tm_back': "🔙 فهرست کشورها",
        'tm_toggled': "{mode} حالا {state} است.",
        'tm_closed_here': "🚫 {mode} برای کشور شما بسته است.",
        'tm_closed_there': "🚫 {mode} برای {g} بسته است.",
        'tm_all_closed': "🚫 هر دو نوع تجارت برای کشور شما بسته است. با مدیریت صحبت کنید.",

        # ============ خطاهای نقشه ============
        'map_err_generic': "خطایی رخ داد.",
        'map_err_bad_mode': "نوع نامعتبر.",
        'map_err_unknown_node': "گره ناشناس.",
        'map_err_no_edge': "یال وجود ندارد.",
        'map_err_bad_id': "شناسه نامعتبر.",
        'map_err_exists': "این شناسه قبلاً وجود دارد.",
        'map_err_bad_kind': "نوع نامعتبر.",
        'map_err_self_edge': "یال به خود مجاز نیست.",
        'map_err_bad_units': "طول باید مثبت باشد.",
        'map_err_edge_exists': "این یال قبلاً وجود دارد.",
        'map_err_in_transit': "محموله‌ای در حال عبور است.",
        'map_err_guard_unavailable': "سیستم محافظ در دسترس نیست.",
        'map_err_reserved': "این شناسه رزرو شده است.",
        'map_bad_number': "عدد نامعتبر.",
        'map_min_number': "عدد باید حداقل {min} باشد.",

        # ============ پنل ویرایش نقشه ============
        'map_title': "🗺 ویرایش نقشه تجارت\n\nکدام نوع را می‌خواهید ببینید؟",
        'map_btn_mode_sea': "🚢 دریایی ({n} گره)",
        'map_btn_mode_land': "🐫 زمینی ({n} گره)",
        'map_mode_sea': "دریایی",
        'map_mode_land': "زمینی",
        'map_btn_prev': "➡️ قبلی",
        'map_btn_next': "بعدی ⬅️",
        'map_nodes_title': "{mode} — گره‌ها (صفحه {p} از {n})",
        'map_edges_title': "{mode} — یال‌ها (صفحه {p} از {n})",
        'map_btn_add_node': "➕ افزودن گره",
        'map_btn_edges': "🔗 یال‌ها",
        'map_btn_add_edge': "➕ افزودن یال",
        'map_btn_back_nodes': "🔙 بازگشت به گره‌ها",
        'map_btn_back_edges': "🔙 بازگشت به یال‌ها",
        'map_btn_back_node': "🔙 بازگشت به گره",
        'map_btn_rename': "✏️ تغییر نام",
        'map_btn_kind': "🏷 تغییر نوع",
        'map_btn_home': "🏠 کلید home",
        'map_btn_toll': "🛣 تنظیم عوارض",
        'map_btn_owner': "👑 مالکیت",
        'map_btn_del_node': "🗑 حذف گره",
        'map_btn_del_yes': "✅ بله، حذف کن",
        'map_btn_units': "📏 طول (واحد)",
        'map_btn_minutes': "⏱ زمان (دقیقه)",
        'map_btn_del_edge': "🗑 حذف یال",
        'map_node': "📍 {name}\nشناسه: {id}\nmode: {mode}\nنوع: {kind}\nhome: {home}\nعوارض: {toll}\nمالک: {owner}\n\n🔗 یال‌ها: {neighbours}",
        'map_edge': "🔗 یال {a} — {b}\nطول: {units} واحد\nزمان: {timing}",
        'map_pick_kind': "نوع جدید را انتخاب کنید:",
        'map_ask_name': "نام جدید ({lang}) را وارد کنید:",
        'map_ask_name_keep': "نام جدید ({lang}) را وارد کنید (فعلی: {current}). خالی = نگه‌داشتن فعلی.",
        'map_name_required': "نام نمی‌تواند خالی باشد.",
        'map_renamed': "✅ نام به‌روزرسانی شد.",
        'map_saved': "✅ ذخیره شد.",
        'map_toll_set': "✅ عوارض {name} روی {val} تنظیم شد.",
        'map_ask_toll': "عوارض جدید {name} را وارد کنید (فعلی: {val}):",
        'map_del_node_confirm': "⚠️ حذف گره {name} ({id})؟\n{links} یال قطع خواهند شد.",
        'map_del_edge_confirm': "⚠️ حذف یال {a} — {b}؟",
        'map_node_deleted': "🗑 گره {name} حذف شد.",
        'map_edge_deleted': "🗑 یال حذف شد.",
        'map_node_added': "✅ گره اضافه شد.",
        'map_edge_added': "✅ یال اضافه شد.",
        'map_home_on': "✅ home روشن شد.",
        'map_home_off': "✅ home خاموش شد.",
        'map_ask_node_id': "شناسه گره جدید را وارد کنید (حروف کوچک، بدون فاصله):",
        'map_ask_node_kind': "نوع گره را انتخاب کنید:",
        'map_ask_node_home': "آیا این گره می‌تواند محل کشور باشد؟",
        'map_ask_edge_first': "گره اول را انتخاب کنید:",
        'map_ask_edge_second': "گره دوم را انتخاب کنید (به جز {name}):",
        'map_ask_edge_units': "طول یال {a} — {b} (واحد):",
        'map_ask_units': "طول جدید یال را وارد کنید:",
        'map_ask_minutes': "زمان جدید یال به دقیقه (0 = خودکار):",
        'map_no_edges': "بدون یال",
        'map_no_owner': "بدون مالک",
        'map_yes': "بله",
        'map_no': "خیر",
        'map_minutes_exact': "{m} دقیقه",
        'map_minutes_auto': "خودکار ({units} واحد)",
        'map_lang_fa': "فارسی",
        'map_lang_en': "انگلیسی",
        'map_lang_tr': "ترکی",
        'map_kind_ocean': "اقیانوس",
        'map_kind_sea': "دریا",
        'map_kind_strait': "تنگه",
        'map_kind_canal': "کانال",
        'map_kind_cape': "دماغه",
        'map_kind_region': "منطقه",
        'map_kind_pass': "گذرگاه",
    },
    'en': {
        # عمومی
        'err_generic': "Something went wrong. Please try again.",
        'session_expired': "Trade session not found. Start again from the «🚢 World Trade» button.",
        'not_registered': "This group has no lord yet. Register first with /setlord.",
        'not_lord': "Only the lord of this group can do that.",
        'admin_only': "You are not the admin.",
        'owner_only': "Only the bot owner can do that.",
        'already_handled': "This offer is no longer valid.",
        # منوی تجارت
        'menu_title': "🌍 World Trade\n\nChoose the type of trade, my lord:",
        'menu_active': "\n\n🧭 Your trades in progress: {n}",
        'btn_sea': "🚢 Sea Trade",
        'btn_land': "🐫 Land Trade",
        'mode_sea': "sea",
        'mode_land': "land",
        'need_home': "🏠 Your group's {mode} location has not been set by the admin yet.",
        'no_dest': "No destination is available for {mode} trade.",
        'choose_dest': "🎯 Choose the trade destination:",
        'btn_cancel': "❌ Cancel",
        'btn_prev': "⬅️ Prev",
        'btn_next': "Next ➡️",
        'btn_back': "🔙 Back",
        # کالاها
        'goods_title': "📦 Choose the goods to trade:\n{lines}\n\n📊 Total cargo volume: {vol}",
        'goods_none': "no goods selected yet",
        'btn_goods_done': "✅ Continue",
        'ask_amount': "Enter the amount of {res} (you have: {bal}):",
        'bad_number': "That is not a valid number.",
        'too_much': "That is more than you have (balance: {bal}).",
        'need_goods': "Select at least one good.",
        # وسایل
        'veh_title_sea': "⚓️ Choose your trade fleet:\n{fleet}\n\n🧾 Your picks:\n{lines}\n\n📦 Cargo volume: {vol}\n🚢 Fleet capacity: {cap}",
        'veh_title_land': "🐫 Prepare your caravan:\n{fleet}\n\n🧾 Your picks:\n{lines}\n\n📦 Cargo volume: {vol}\n🐫 Caravan capacity: {cap}\n💵 Cost per caravan: {p}",
        'ask_vcount': "Enter the number of {v} (you own: {bal} | each carries: {cap}):",
        'veh_row': "{name}: carries {cap} each — you own {own}",
        'ask_caravans': "Enter the number of caravans (you own: {bal} | each carries: {cap} | each costs {p}):",
        'not_enough_units': "That is more than you own (you have: {bal}).",
        'not_enough_cap': "Not enough capacity! Cargo volume is {vol} but capacity is only {cap}.",
        'btn_veh_done': "🗺 Compute routes",
        # مسیر
        'routes_title': "🗺 Suggested routes from {src} to {dst}:",
        'route_fast': "⚡️ Fastest route",
        'route_free': "🆓 Toll-free route",
        'route_cheap': "💰 Cheapest route",
        'route_block': "{label}\n⏱ Duration: {dur}\n🧭 Route: {path}\n💵 Base fee: {fee}\n🪙 Tolls: {tolls}\n💰 Total: {total}",
        'tolls_none': "none",
        'no_route': "No route found between these two locations!",
        'btn_route': "Choose route {i}",
        'path_arrow': " → ",
        # تأیید
        'confirm_title': "📜 Trade summary:\n🎯 Destination: {dest}\n📦 Goods:\n{goods}\n🚛 Vehicles: {veh}\n🧭 Route: {path}\n⏱ Duration: {dur}\n💰 Total cost: {cost}\n\nDo you confirm?",
        'btn_send': "✅ Send offer",
        'insufficient': "💸 You do not have enough for this trade.",
        'offer_sent_sender': "📨 Trade offer #{tid} was sent to {dest}. Awaiting acceptance...",
        'btn_cancel_offer': "🚫 Cancel offer",
        'send_failed': "Could not deliver the offer; everything was refunded.",
        # پیشنهاد
        'offer_msg': "📦 Trade offer #{tid}\n\n🌍 From: {sender}\n👤 Lord: {lord}\n\n📦 Goods:\n{goods}\n\n🧭 Route: {path}\n⏱ Travel time: {dur}\n⌛️ Offer expires in: {exp} minutes\n\nDo you accept?",
        'btn_accept': "✅ Accept",
        'btn_decline': "❌ Decline",
        'offer_accepted_edit': "\n\n✅ Accepted — the shipment is on its way!",
        'offer_declined_edit': "\n\n❌ Declined.",
        'offer_cancelled_edit': "\n\n🚫 Cancelled by the sender.",
        'offer_expired_edit': "\n\n⌛️ The offer expired.",
        'declined_sender': "❌ Trade offer #{tid} was declined; goods and fees refunded.",
        'cancelled_sender': "🚫 Trade offer #{tid} was cancelled; refunded.",
        'expired_sender': "⌛️ Trade offer #{tid} expired; refunded.",
        # ردیابی
        'track_header': "{emoji} Trade #{tid} | {src_g} → {dst_g}",
        'track_moving': "🧭 Heading toward {next} (about {min} minutes)",
        'track_at': "📍 Current position: {cur}",
        'track_choke': "🪙 The shipment passed {cur} (toll paid)",
        'track_cape': "🌊 The shipment rounded {cur}",
        'track_done': "✅ The shipment arrived and the goods were delivered!",
        'track_choke_owned': "🪙 The shipment passed {cur} — toll paid to {owner}",
        'track_pass': "🌫 The shipment passed {cur}",
        'arrived_receiver': "📦 Shipment #{tid} from {sender} has arrived!\n{goods}",
        'depart_channel': "{emoji} A trade shipment departed from {src_g} toward {dst_g}!\n\n🧭 Route: {path}\n⏱ Estimated arrival: {dur}",
        'arrive_channel': "{emoji} The trade shipment from {src_g} arrived at {dst_g}!",
        # زمان
        'dur_hm': "{h}h {m}m",
        'dur_m': "{m} minutes",
        'wizard_cancelled': "🚫 Trade cancelled.",
        # پنل ادمین
        'adm_title': "🌍 Trade administration:",
        'btn_home_sea': "⚓️ Set groups' sea locations",
        'btn_home_land': "🏔 Set groups' land locations",
        'btn_cfg': "⚙️ Trade settings",
        'btn_owners': "🪙 Chokepoint ownership",
        'btn_map': "🗺 Edit the trade map",
        'adm_pick_group': "Choose a group:",
        'adm_pick_node': "Choose the {mode} location for {g}:",
        'home_set': "🏠 The {mode} location of {g} was set to «{node}».",
        'adm_no_groups': "No country is registered yet.",
        # مالکیت
        'own_title': "🪙 Chokepoints (page {p}) — tap one to set its owner:",
        'own_unowned': "unowned",
        'own_pick': "Choose the owner of {node}:",
        'btn_no_owner': "🚫 No owner",
        'own_set': "🪙 {node} is now owned by {g}.",
        'own_cleared': "🪙 {node} is now unowned.",
        'toll_income': "🪙 Your treasury collected {amount} money in tolls!",
        # تنظیمات
        'cfg_home': "⚙️ Trade settings — which section?",
        'cfg_sec_journey': "⏱ Journeys and fees ({n})",
        'cfg_sec_capacity': "📦 Vehicle capacity and cost ({n})",
        'cfg_sec_toll': "🛣 Chokepoint tolls ({n})",
        'cfg_sec_name_journey': "journeys and fees",
        'cfg_sec_name_capacity': "vehicle capacity and cost",
        'cfg_sec_name_toll': "chokepoint tolls",
        'cfg_sec_empty': "There is nothing to set here.",
        'cfg_title': "⚙️ Trade settings — {section} (page {p} of {n})\nTap a setting:",
        'cfg_row': "**{name}** — now: `{val}`\n{help}",
        'cfg_ask': "**{name}**\n{help}\n\nCurrent: {val}\nSend new:",
        'cfg_set': "✅ {name} set to {val}.",
        'cfg_toll_label': "🛣 Toll at {node}",
        'cfg_toll_help': "What every convoy passing this chokepoint pays.",
        'btn_cfg_back': "🔙 Setting groups",
        # نام تنظیمات
        'sea_min_per_unit': "⏱ Sea travel time",
        'land_min_per_unit': "⏱ Land travel time",
        'fee_per_unit': "💵 Route fee",
        'offer_expiry_min': "⌛️ Offer expiry",
        'cap_small': "⛵ Small ship cargo capacity",
        'cap_medium': "🚢 Medium ship cargo capacity",
        'cap_large': "🛳 Large ship cargo capacity",
        'cap_caravan': "🐫 Cargo capacity per caravan",
        'caravan_cost': "💰 Cost per caravan per trip",
        # توضیح تنظیمات
        'help_sea_min_per_unit': "Minutes a sea convoy takes to cross one unit of distance.",
        'help_land_min_per_unit': "Minutes a caravan takes to cross one unit of distance.",
        'help_fee_per_unit': "Money charged per unit of route length.",
        'help_offer_expiry_min': "If the receiver has not answered within this many minutes, the offer lapses.",
        'help_cap_small': "How many units one small ship carries.",
        'help_cap_medium': "How many units one medium ship carries.",
        'help_cap_large': "How many units one large ship carries.",
        'help_cap_caravan': "How many units one caravan carries.",
        'help_caravan_cost': "Money charged for each caravan sent on a trip.",
        # عکس
        'btn_photo': "🖼 Trade photo",
        'btn_ph_mode_sea': "🚢 Sea trade photo — {state}",
        'btn_ph_mode_land': "🐫 Land trade photo — {state}",
        'btn_ph_mode_both': "🖼 Shared photo — {state}",
        'btn_ph_back': "🔙 Back to photos",
        'ph_home': "🖼 Trade photo — which one?",
        'ph_mode_sea': "sea trade",
        'ph_mode_land': "land trade",
        'ph_mode_both': "shared photo",
        'ph_shared': "using shared photo",
        'ph_title': "🖼 Photo for {mode} — currently: {state}",
        'ph_set': "set",
        'ph_unset': "not set",
        'btn_ph_set': "📷 Set photo",
        'btn_ph_clear': "🗑 Remove photo",
        'ph_ask': "Send the photo for {mode} now:",
        'ph_saved': "✅ Photo saved.",
        'ph_cleared': "🗑 Photo removed.",
        'ph_not_photo': "That message is not a photo.",
        # باز/بسته
        'btn_trade_modes': "🚧 Open/close a country's trade",
        'tm_title': "🚧 Trade per country (page {p} of {n}):",
        'tm_group': "🚧 **{g}**\n{lines}",
        'tm_row': "{mode}: {state}",
        'tm_on': "{mode}✅",
        'tm_off': "{mode}🚫",
        'tm_state_on': "open",
        'tm_state_off': "closed",
        'btn_tm_close': "🚫 Close {mode}",
        'btn_tm_open': "✅ Open {mode}",
        'btn_tm_back': "🔙 Country list",
        'tm_toggled': "{mode} is now {state}.",
        'tm_closed_here': "🚫 {mode} is closed for your country.",
        'tm_closed_there': "🚫 {mode} is closed for {g}.",
        'tm_all_closed': "🚫 Both kinds of trade are closed for your country.",
        # خطاهای نقشه
        'map_err_generic': "An error occurred.",
        'map_err_bad_mode': "Invalid mode.",
        'map_err_unknown_node': "Unknown node.",
        'map_err_no_edge': "Edge not found.",
        'map_err_bad_id': "Invalid id.",
        'map_err_exists': "This id already exists.",
        'map_err_bad_kind': "Invalid kind.",
        'map_err_self_edge': "Self-edge is not allowed.",
        'map_err_bad_units': "Length must be positive.",
        'map_err_edge_exists': "This edge already exists.",
        'map_err_in_transit': "A shipment is in transit.",
        'map_err_guard_unavailable': "Guard system unavailable.",
        'map_err_reserved': "This id is reserved.",
        'map_bad_number': "Invalid number.",
        'map_min_number': "Must be at least {min}.",
        # پنل نقشه
        'map_title': "🗺 Edit the trade map\n\nWhich mode?",
        'map_btn_mode_sea': "🚢 Sea ({n} nodes)",
        'map_btn_mode_land': "🐫 Land ({n} nodes)",
        'map_mode_sea': "sea",
        'map_mode_land': "land",
        'map_btn_prev': "⬅️ Prev",
        'map_btn_next': "Next ➡️",
        'map_nodes_title': "{mode} — nodes (page {p} of {n})",
        'map_edges_title': "{mode} — edges (page {p} of {n})",
        'map_btn_add_node': "➕ Add node",
        'map_btn_edges': "🔗 Edges",
        'map_btn_add_edge': "➕ Add edge",
        'map_btn_back_nodes': "🔙 Back to nodes",
        'map_btn_back_edges': "🔙 Back to edges",
        'map_btn_back_node': "🔙 Back to node",
        'map_btn_rename': "✏️ Rename",
        'map_btn_kind': "🏷 Change kind",
        'map_btn_home': "🏠 Toggle home",
        'map_btn_toll': "🛣 Set toll",
        'map_btn_owner': "👑 Ownership",
        'map_btn_del_node': "🗑 Delete node",
        'map_btn_del_yes': "✅ Yes, delete",
        'map_btn_units': "📏 Length (units)",
        'map_btn_minutes': "⏱ Time (minutes)",
        'map_btn_del_edge': "🗑 Delete edge",
        'map_node': "📍 {name}\nID: {id}\nmode: {mode}\nkind: {kind}\nhome: {home}\ntoll: {toll}\nowner: {owner}\n\n🔗 Edges: {neighbours}",
        'map_edge': "🔗 Edge {a} — {b}\nLength: {units} units\nTime: {timing}",
        'map_pick_kind': "Choose new kind:",
        'map_ask_name': "Enter new name ({lang}):",
        'map_ask_name_keep': "Enter new name ({lang}) (current: {current}). Empty = keep.",
        'map_name_required': "Name cannot be empty.",
        'map_renamed': "✅ Name updated.",
        'map_saved': "✅ Saved.",
        'map_toll_set': "✅ Toll for {name} set to {val}.",
        'map_ask_toll': "New toll for {name} (current: {val}):",
        'map_del_node_confirm': "⚠️ Delete node {name} ({id})?\n{links} edges will be cut.",
        'map_del_edge_confirm': "⚠️ Delete edge {a} — {b}?",
        'map_node_deleted': "🗑 Node {name} deleted.",
        'map_edge_deleted': "🗑 Edge deleted.",
        'map_node_added': "✅ Node added.",
        'map_edge_added': "✅ Edge added.",
        'map_home_on': "✅ home on.",
        'map_home_off': "✅ home off.",
        'map_ask_node_id': "Enter new node id (lowercase, no spaces):",
        'map_ask_node_kind': "Choose node kind:",
        'map_ask_node_home': "Can this node be a home?",
        'map_ask_edge_first': "Choose first node:",
        'map_ask_edge_second': "Choose second node (except {name}):",
        'map_ask_edge_units': "Length of edge {a} — {b} (units):",
        'map_ask_units': "Enter new length:",
        'map_ask_minutes': "New time in minutes (0 = auto):",
        'map_no_edges': "no edges",
        'map_no_owner': "no owner",
        'map_yes': "yes",
        'map_no': "no",
        'map_minutes_exact': "{m} minutes",
        'map_minutes_auto': "auto ({units} units)",
        'map_lang_fa': "Persian",
        'map_lang_en': "English",
        'map_lang_tr': "Turkish",
        'map_kind_ocean': "ocean",
        'map_kind_sea': "sea",
        'map_kind_strait': "strait",
        'map_kind_canal': "canal",
        'map_kind_cape': "cape",
        'map_kind_region': "region",
        'map_kind_pass': "pass",
    },
    'tr': {
        # عمومی
        'err_generic': "Bir hata oluştu.",
        'session_expired': "Ticaret oturumu bulunamadı.",
        'not_registered': "Bu grubun henüz bir lordu yok.",
        'not_lord': "Bunu yalnızca bu grubun lordu yapabilir.",
        'admin_only': "Yönetici değilsiniz.",
        'owner_only': "Bunu yalnızca bot sahibi yapabilir.",
        'already_handled': "Bu teklif artık geçerli değil.",
        # منو
        'menu_title': "🌍 Dünya Ticareti\n\nTicaret türünü seçin lordum:",
        'menu_active': "\n\n🧭 Devam eden ticaretleriniz: {n}",
        'btn_sea': "🚢 Deniz Ticareti",
        'btn_land': "🐫 Kara Ticareti",
        'mode_sea': "deniz",
        'mode_land': "kara",
        'need_home': "🏠 Grubunuzun {mode} konumu henüz belirlenmedi.",
        'no_dest': "{mode} ticareti için uygun hedef yok.",
        'choose_dest': "🎯 Ticaret hedefini seçin:",
        'btn_cancel': "❌ İptal",
        'btn_prev': "⬅️ Önceki",
        'btn_next': "Sonraki ➡️",
        'btn_back': "🔙 Geri",
        # کالاها
        'goods_title': "📦 Ticaret mallarını seçin:\n{lines}\n\n📊 Toplam yük: {vol}",
        'goods_none': "henüz mal seçilmedi",
        'btn_goods_done': "✅ Devam",
        'ask_amount': "{res} miktarını girin (mevcut: {bal}):",
        'bad_number': "Geçersiz sayı.",
        'too_much': "Sahip olduğunuzdan fazla (mevcut: {bal}).",
        'need_goods': "En az bir mal seçin.",
        # وسایل
        'veh_title_sea': "⚓️ Ticaret filonuzu seçin:\n{fleet}\n\n🧾 Seçiminiz:\n{lines}\n\n📦 Yük: {vol}\n🚢 Kapasite: {cap}",
        'veh_title_land': "🐫 Kervanınızı hazırlayın:\n{fleet}\n\n🧾 Seçiminiz:\n{lines}\n\n📦 Yük: {vol}\n🐫 Kapasite: {cap}\n💵 Kervan maliyeti: {p}",
        'ask_vcount': "{v} sayısını girin (sahip: {bal} | her biri: {cap}):",
        'veh_row': "{name}: her biri {cap} taşır — sahip olduğunuz {own}",
        'ask_caravans': "Kervan sayısını girin (sahip: {bal} | her biri: {cap} | her biri: {p}):",
        'not_enough_units': "Sahip olduğunuzdan fazla (mevcut: {bal}).",
        'not_enough_cap': "Kapasite yetersiz! Yük {vol} ama kapasite {cap}.",
        'btn_veh_done': "🗺 Rotaları hesapla",
        # مسیر
        'routes_title': "🗺 {src} → {dst} için rotalar:",
        'route_fast': "⚡️ En hızlı",
        'route_free': "🆓 Ücretsiz",
        'route_cheap': "💰 En ucuz",
        'route_block': "{label}\n⏱ Süre: {dur}\n🧭 Rota: {path}\n💵 Ücret: {fee}\n🪙 Geçişler: {tolls}\n💰 Toplam: {total}",
        'tolls_none': "yok",
        'no_route': "Rota bulunamadı!",
        'btn_route': "Rota {i}",
        'path_arrow': " → ",
        # تأیید
        'confirm_title': "📜 Ticaret özeti:\n🎯 Hedef: {dest}\n📦 Mallar:\n{goods}\n🚛 Araçlar: {veh}\n🧭 Rota: {path}\n⏱ Süre: {dur}\n💰 Toplam: {cost}\n\nOnaylıyor musunuz?",
        'btn_send': "✅ Teklifi gönder",
        'insufficient': "💸 Yeterli kaynağınız yok.",
        'offer_sent_sender': "📨 #{tid} teklifi {dest} grubuna gönderildi.",
        'btn_cancel_offer': "🚫 İptal",
        'send_failed': "Teklif gönderilemedi; iade edildi.",
        # پیشنهاد
        'offer_msg': "📦 Ticaret teklifi #{tid}\n\n🌍 Gönderen: {sender}\n👤 Lord: {lord}\n\n📦 Mallar:\n{goods}\n\n🧭 Rota: {path}\n⏱ Süre: {dur}\n⌛️ Geçerlilik: {exp} dakika\n\nKabul ediyor musunuz?",
        'btn_accept': "✅ Kabul",
        'btn_decline': "❌ Reddet",
        'offer_accepted_edit': "\n\n✅ Kabul edildi — sevkiyat yolda!",
        'offer_declined_edit': "\n\n❌ Reddedildi.",
        'offer_cancelled_edit': "\n\n🚫 İptal edildi.",
        'offer_expired_edit': "\n\n⌛️ Süre doldu.",
        'declined_sender': "❌ #{tid} reddedildi; iade edildi.",
        'cancelled_sender': "🚫 #{tid} iptal edildi; iade edildi.",
        'expired_sender': "⌛️ #{tid} süresi doldu; iade edildi.",
        # ردیابی
        'track_header': "{emoji} Ticaret #{tid} | {src_g} → {dst_g}",
        'track_moving': "🧭 {next} yönünde ({min} dakika)",
        'track_at': "📍 Konum: {cur}",
        'track_choke': "🪙 {cur} geçildi (ücret ödendi)",
        'track_cape': "🌊 {cur} dolaşıldı",
        'track_done': "✅ Sevkiyat ulaştı!",
        'track_choke_owned': "🪙 {cur} geçildi — ücret {owner} grubuna ödendi",
        'track_pass': "🌫 {cur} geçildi",
        'arrived_receiver': "📦 #{tid} sevkiyatı {sender} grubundan ulaştı!\n{goods}",
        'depart_channel': "{emoji} {src_g} grubundan {dst_g} hedefine sevkiyat yola çıktı!\n\n🧭 Rota: {path}\n⏱ Tahmini varış: {dur}",
        'arrive_channel': "{emoji} {src_g} grubundan gelen sevkiyat {dst_g} hedefine ulaştı!",
        # زمان
        'dur_hm': "{h} sa {m} dk",
        'dur_m': "{m} dakika",
        'wizard_cancelled': "🚫 Ticaret iptal edildi.",
        # ادمین
        'adm_title': "🌍 Ticaret yönetimi:",
        'btn_home_sea': "⚓️ Deniz konumlarını ayarla",
        'btn_home_land': "🏔 Kara konumlarını ayarla",
        'btn_cfg': "⚙️ Ticaret ayarları",
        'btn_owners': "🪙 Boğaz sahipliği",
        'btn_map': "🗺 Haritayı düzenle",
        'adm_pick_group': "Grup seçin:",
        'adm_pick_node': "{g} için {mode} konumunu seçin:",
        'home_set': "🏠 {g} grubunun {mode} konumu «{node}» olarak ayarlandı.",
        'adm_no_groups': "Kayıtlı ülke yok.",
        # مالکیت
        'own_title': "🪙 Boğazlar (sayfa {p}):",
        'own_unowned': "sahipsiz",
        'own_pick': "{node} sahibini seçin:",
        'btn_no_owner': "🚫 Sahipsiz",
        'own_set': "🪙 {node} artık {g} grubuna ait.",
        'own_cleared': "🪙 {node} artık sahipsiz.",
        'toll_income': "🪙 Hazineniz {amount} para topladı!",
        # تنظیمات
        'cfg_home': "⚙️ Ticaret ayarları — hangi bölüm?",
        'cfg_sec_journey': "⏱ Yolculuk ve ücretler ({n})",
        'cfg_sec_capacity': "📦 Araç kapasitesi ({n})",
        'cfg_sec_toll': "🛣 Geçit ücretleri ({n})",
        'cfg_sec_name_journey': "yolculuk ve ücretler",
        'cfg_sec_name_capacity': "araç kapasitesi",
        'cfg_sec_name_toll': "geçit ücretleri",
        'cfg_sec_empty': "Bu grupta ayar yok.",
        'cfg_title': "⚙️ Ticaret ayarları — {section} ({p}/{n}):",
        'cfg_row': "**{name}** — şu an: `{val}`\n{help}",
        'cfg_ask': "**{name}**\n{help}\n\nMevcut: {val}\nYenisini gönderin:",
        'cfg_set': "✅ {name} {val} olarak ayarlandı.",
        'cfg_toll_label': "🛣 {node} ücreti",
        'cfg_toll_help': "Bu geçitten geçen her konvoyun ödediği ücret.",
        'btn_cfg_back': "🔙 Ayar grupları",
        # نام تنظیمات
        'sea_min_per_unit': "⏱ Deniz yolculuk süresi",
        'land_min_per_unit': "⏱ Kara yolculuk süresi",
        'fee_per_unit': "💵 Rota ücreti",
        'offer_expiry_min': "⌛️ Teklif süresi",
        'cap_small': "⛵ Küçük gemi kapasitesi",
        'cap_medium': "🚢 Orta gemi kapasitesi",
        'cap_large': "🛳 Büyük gemi kapasitesi",
        'cap_caravan': "🐫 Kervan kapasitesi",
        'caravan_cost': "💰 Kervan maliyeti",
        # توضیح
        'help_sea_min_per_unit': "Bir deniz konvoyunun bir birim mesafeyi geçme süresi.",
        'help_land_min_per_unit': "Bir kervanın bir birim mesafeyi geçme süresi.",
        'help_fee_per_unit': "Rota uzunluğunun her birimi için alınan para.",
        'help_offer_expiry_min': "Alıcı bu kadar dakika içinde yanıt vermezse teklif düşer.",
        'help_cap_small': "Bir küçük geminin taşıdığı yük birimi.",
        'help_cap_medium': "Bir orta geminin taşıdığı yük birimi.",
        'help_cap_large': "Bir büyük geminin taşıdığı yük birimi.",
        'help_cap_caravan': "Bir kervanın taşıdığı yük birimi.",
        'help_caravan_cost': "Sefere çıkan her kervan için alınan para.",
        # عکس
        'btn_photo': "🖼 Ticaret fotoğrafı",
        'btn_ph_mode_sea': "🚢 Deniz fotoğrafı — {state}",
        'btn_ph_mode_land': "🐫 Kara fotoğrafı — {state}",
        'btn_ph_mode_both': "🖼 Ortak fotoğraf — {state}",
        'btn_ph_back': "🔙 Fotoğraflara dön",
        'ph_home': "🖼 Ticaret fotoğrafı — hangisi?",
        'ph_mode_sea': "deniz ticareti",
        'ph_mode_land': "kara ticareti",
        'ph_mode_both': "ortak fotoğraf",
        'ph_shared': "ortak kullanılıyor",
        'ph_title': "🖼 {mode} fotoğrafı — şu an: {state}",
        'ph_set': "ayarlandı",
        'ph_unset': "ayarlanmadı",
        'btn_ph_set': "📷 Ayar",
        'btn_ph_clear': "🗑 Kaldır",
        'ph_ask': "{mode} için fotoğraf gönderin:",
        'ph_saved': "✅ Kaydedildi.",
        'ph_cleared': "🗑 Kaldırıldı.",
        'ph_not_photo': "Bu bir fotoğraf değil.",
        # باز/بسته
        'btn_trade_modes': "🚧 Ülke ticaretini aç/kapat",
        'tm_title': "🚧 Ülke ticareti ({p}/{n}):",
        'tm_group': "🚧 **{g}**\n{lines}",
        'tm_row': "{mode}: {state}",
        'tm_on': "{mode}✅",
        'tm_off': "{mode}🚫",
        'tm_state_on': "açık",
        'tm_state_off': "kapalı",
        'btn_tm_close': "🚫 {mode} kapat",
        'btn_tm_open': "✅ {mode} aç",
        'btn_tm_back': "🔙 Ülke listesi",
        'tm_toggled': "{mode} artık {state}.",
        'tm_closed_here': "🚫 Ülkeniz için {mode} kapalı.",
        'tm_closed_there': "🚫 {g} için {mode} kapalı.",
        'tm_all_closed': "🚫 Her iki ticaret türü de kapalı.",
        # خطاهای نقشه
        'map_err_generic': "Hata oluştu.",
        'map_err_bad_mode': "Geçersiz mod.",
        'map_err_unknown_node': "Bilinmeyen düğüm.",
        'map_err_no_edge': "Kenar bulunamadı.",
        'map_err_bad_id': "Geçersiz id.",
        'map_err_exists': "Bu id zaten var.",
        'map_err_bad_kind': "Geçersiz tür.",
        'map_err_self_edge': "Kendine kenar olmaz.",
        'map_err_bad_units': "Uzunluk pozitif olmalı.",
        'map_err_edge_exists': "Bu kenar zaten var.",
        'map_err_in_transit': "Sevkiyat yolda.",
        'map_err_guard_unavailable': "Koruma sistemi yok.",
        'map_err_reserved': "Bu id ayrılmış.",
        'map_bad_number': "Geçersiz sayı.",
        'map_min_number': "En az {min} olmalı.",
        # پنل نقشه
        'map_title': "🗺 Haritayı düzenle\n\nHangi mod?",
        'map_btn_mode_sea': "🚢 Deniz ({n} düğüm)",
        'map_btn_mode_land': "🐫 Kara ({n} düğüm)",
        'map_mode_sea': "deniz",
        'map_mode_land': "kara",
        'map_btn_prev': "⬅️ Önceki",
        'map_btn_next': "Sonraki ➡️",
        'map_nodes_title': "{mode} — düğümler ({p}/{n})",
        'map_edges_title': "{mode} — kenarlar ({p}/{n})",
        'map_btn_add_node': "➕ Düğüm ekle",
        'map_btn_edges': "🔗 Kenarlar",
        'map_btn_add_edge': "➕ Kenar ekle",
        'map_btn_back_nodes': "🔙 Düğümlere dön",
        'map_btn_back_edges': "🔙 Kenarlara dön",
        'map_btn_back_node': "🔙 Düğüme dön",
        'map_btn_rename': "✏️ Yeniden adlandır",
        'map_btn_kind': "🏷 Tür değiştir",
        'map_btn_home': "🏠 home değiştir",
        'map_btn_toll': "🛣 Ücret ayarla",
        'map_btn_owner': "👑 Sahiplik",
        'map_btn_del_node': "🗑 Düğümü sil",
        'map_btn_del_yes': "✅ Evet, sil",
        'map_btn_units': "📏 Uzunluk",
        'map_btn_minutes': "⏱ Süre (dakika)",
        'map_btn_del_edge': "🗑 Kenarı sil",
        'map_node': "📍 {name}\nID: {id}\nmod: {mode}\ntür: {kind}\nhome: {home}\nücret: {toll}\nsahip: {owner}\n\n🔗 Kenarlar: {neighbours}",
        'map_edge': "🔗 Kenar {a} — {b}\nUzunluk: {units}\nSüre: {timing}",
        'map_pick_kind': "Yeni tür:",
        'map_ask_name': "Yeni ad ({lang}):",
        'map_ask_name_keep': "Yeni ad ({lang}) (şu an: {current}). Boş = koru.",
        'map_name_required': "Ad boş olamaz.",
        'map_renamed': "✅ Ad güncellendi.",
        'map_saved': "✅ Kaydedildi.",
        'map_toll_set': "✅ {name} ücreti {val} yapıldı.",
        'map_ask_toll': "{name} için yeni ücret (şu an: {val}):",
        'map_del_node_confirm': "⚠️ {name} ({id}) silinsin mi?\n{links} kenar kesilecek.",
        'map_del_edge_confirm': "⚠️ {a} — {b} kenarı silinsin mi?",
        'map_node_deleted': "🗑 {name} silindi.",
        'map_edge_deleted': "🗑 Kenar silindi.",
        'map_node_added': "✅ Düğüm eklendi.",
        'map_edge_added': "✅ Kenar eklendi.",
        'map_home_on': "✅ home açık.",
        'map_home_off': "✅ home kapalı.",
        'map_ask_node_id': "Yeni düğüm id girin (küçük harf):",
        'map_ask_node_kind': "Düğüm türü:",
        'map_ask_node_home': "Bu düğüm home olabilir mi?",
        'map_ask_edge_first': "İlk düğümü seçin:",
        'map_ask_edge_second': "İkinci düğümü seçin ({name} hariç):",
        'map_ask_edge_units': "{a} — {b} kenarı uzunluğu:",
        'map_ask_units': "Yeni uzunluk:",
        'map_ask_minutes': "Yeni süre dakika (0 = otomatik):",
        'map_no_edges': "kenar yok",
        'map_no_owner': "sahipsiz",
        'map_yes': "evet",
        'map_no': "hayır",
        'map_minutes_exact': "{m} dakika",
        'map_minutes_auto': "otomatik ({units} unit)",
        'map_lang_fa': "Farsça",
        'map_lang_en': "İngilizce",
        'map_lang_tr': "Türkçe",
        'map_kind_ocean': "okyanus",
        'map_kind_sea': "deniz",
        'map_kind_strait': "boğaz",
        'map_kind_canal': "kanal",
        'map_kind_cape': "burun",
        'map_kind_region': "bölge",
        'map_kind_pass': "geçit",
    },
}


# بررسی یکسان بودن کلیدها در init
def check_keys():
    fa = set(STRINGS['fa'].keys())
    en = set(STRINGS['en'].keys())
    tr = set(STRINGS['tr'].keys())
    missing_en = fa - en
    missing_tr = fa - tr
    if missing_en:
        print(f"⚠️  کلیدهای موجود در fa ولی نه en: {missing_en}")
    if missing_tr:
        print(f"⚠️  کلیدهای موجود در fa ولی نه tr: {missing_tr}")
    return not (missing_en or missing_tr)


if __name__ == '__main__':
    check_keys()
